name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Now that you've submitted your first issue, you've indicated your interest, 
        an admin will send an invitation to your GitHub account & email for you to join the organization.
We are in the midst of setting up an automated GitHub Actions pipeline to automatically invite users when 
they raise an issue or submit a PR, in the future.
After joining this organization, please do the following:
Click here
Then click on 'People' tab
Next, toggle your organization visibility from 'Private' to 'Public'.
Admins/Owners of the organization are free to invite any other GitHub users to the organization.
"
"
        pr-message: "Hello & welcome to your first open source project. Now that you've 
        submitted a pull-request you must wait for your PR to be reviewed, approved & 
        merged by an admin/owner.
If there are issues with your PR, please revise them in accordance to the comments made by the admins.
How to join this organization?
To indicate your interest in joining this organization, kindly do one of the following:
a) Star this repo
b) Submit a PR
c) Raise an issue titled 'I wish to join this organization'
