on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.3
        with:
          organization: Your-First-Open-Source-Project
          label: invite me to the organization
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: |
            Hello there 👋🏻, Welcome to our community!
            Thank you for your interest in 'Your First Open Source Project'!
            Please take note of the following:
            - Accept the invitation sent to you via email.
            - Change the appearance of this organization to 'Public' over [here](https://github.com/orgs/Your-First-Open-Source-Project/people).
            - Feel free to ask questions in the 'Discussions' tab
            - Be nice, courteous and friendly to everyone in this group 😊
            - Hope to see your first PR to the organization soon :)
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
